/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Preferences = IDL.Record({
  'customRestMinutes' : IDL.Nat,
  'background' : IDL.Text,
  'displayMode' : IDL.Text,
  'selectedPreset' : IDL.Text,
  'customWorkMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllPreferences' : IDL.Func([], [IDL.Vec(Preferences)], ['query']),
  'getPreferences' : IDL.Func([], [Preferences], ['query']),
  'updatePreferences' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Preferences = IDL.Record({
    'customRestMinutes' : IDL.Nat,
    'background' : IDL.Text,
    'displayMode' : IDL.Text,
    'selectedPreset' : IDL.Text,
    'customWorkMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllPreferences' : IDL.Func([], [IDL.Vec(Preferences)], ['query']),
    'getPreferences' : IDL.Func([], [Preferences], ['query']),
    'updatePreferences' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };